Columns Highlight: Video implementation
adobe/express-website pull request #307
Opened 2022-01-15 07:17 UTC by williambsm

I've imported the identical video player from the tutorials block into the columns block. It seems to follow the specs recommended. 

As per the discussion with Raphael, this functionality is only enabled for highlight column blocks.

I did not add the hover animation as it is marked as optional, and I am struggling to place the overlay due to the div and image have no set height. I will continue to work on this and if PR is not merged by then, I will commit the feature addition.

I feel like the .video-overlay part could potentially be placed within its own global css file and the JS could probably be exported and used globally as well, but for now I restricted myself to only implementing it for this block.

You can test the implementation here:

https://main--express-website--adobe.hlx3.page/drafts/nipun/registration-vimeo

2022-01-15 09:08 UTC, rofe requested changes
Following the example of the `/express/blocks/shared/carousel.js`, I'd move the common, generic methods `playInlineVideo()`, `hideVideo()` and `displayVideo()` into a shared `video.js` module and then remove & import them from both the `tutorials` and the columns `block`. The CSS can stay duplicated per block for now, but theoretically we could also load that in a separate snippet from the shared module.

2022-01-15 09:08 UTC, rofe commented on express/blocks/columns/columns.js
> +        if ($a.href.includes('vimeo') && $row.parentElement.classList.contains('highlight')) {
`displayVideo()` can handle YT videos, too, so let's add it here pre-emptively.
```suggestion
        if (($a.href.includes('vimeo') || $a.href.includes('youtu'))
          && $row.parentElement.classList.contains('highlight')) {
```

2022-01-15 11:01 UTC, rofe commented
Also, I think the content for this block variant is wrong: instead of adding a separate link in the thumbnail cell, we should change the CTA link (it makes little sense for the "watch the session" CTA to not link to the video). 

And as discussed with @timliu-adobe in person, once a video-like CTA link is detected, the entire row (both the thumbnail and text cell) should become a link to trigger the video player. Unfortunately this wasn't clearly conveyed in the issue description. I added it now.

2022-01-18 08:28 UTC, timliu-adobe commented
Ah, apologies for any confusion regarding the issue description; thank you for adding in that detail @rofe. Thank you for the support on this @williambsm!

2022-01-18 15:36 UTC, rofe approved these changes
@williambsm this looks great! As discussed, try to get the hover state in as well before we merge this into prod.

2022-01-18 20:12 UTC, rofe commented
Still working on getting the hover state to work on all breakpoints. Will be delivered later.

2022-01-18 20:12 UTC, merged