Japanese balanced word wrap
adobe/express-website pull request #370
Opened 2022-03-15 10:03 UTC by MasonPinZ

This is the logic to make Japanese headings wrap at positions so that the lines after word wrapping have more balanced lengths.

Before this change:
<img width="500" alt="Screen Shot 2022-03-15 at 18 39 42" src="https://user-images.githubusercontent.com/12515123/158349912-c7654c79-2d02-4ce3-bd76-31a8f3a94588.png">

After this change:
<img width="500" alt="Screen Shot 2022-03-15 at 18 39 20" src="https://user-images.githubusercontent.com/12515123/158350014-7afe605f-0c48-4a23-9a34-e8415b7dd825.png">

## Description

The logic uses [CanvasRenderingContext2D](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) to measure actual text width, decides where to break lines based on the text width and existing `<wbr>` tag locations, and uses CSS style classes to switch on/off the `<wbr>` tags in [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver) callback functions.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-03-15 11:11 UTC, tripodsan requested changes
it seems that something gets lost:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/917628/158365522-33798059-7a51-439a-bf4f-8ae6e3b8f97d.png">

https://pianomister.github.io/diffsite/?url1=https%3A%2F%2Fjpn-balanced-word-wrap--express-website--masonpinz.hlx3.page%2Fjp%2Fexpress%2Ffeature&url2=https%3A%2F%2Fmain--express-website--adobe.hlx3.page%2Fjp%2Fexpress%2Ffeature

2022-03-16 07:31 UTC, rofe commented
@MasonPinZ there seems to be a pretty significant difference in total blocking time between this branch and `main`, which is affecting the lighthouse score:
- `main`: https://pagespeed.web.dev/report?url=https%3A%2F%2Fmain--express-website--masonpinz.hlx3.page%2Fjp%2Fexpress%2Ffeature%3Flighthouse%3Don
- `jpn-balanced-word-wrap`: https://pagespeed.web.dev/report?url=https%3A%2F%2Fjpn-balanced-word-wrap--express-website--masonpinz.hlx3.page%2Fjp%2Fexpress%2Ffeature%3Flighthouse%3Don

I can only assume it has to do with what's going on inside `bw.js`. Do you see a way to optimize the code do reduce blocking time?

2022-03-16 07:51 UTC, MasonPinZ commented
> @MasonPinZ there seems to be a pretty significant difference in total blocking time between this branch and `main`, which is affecting the lighthouse score:
> 
> * `main`: https://pagespeed.web.dev/report?url=https%3A%2F%2Fmain--express-website--masonpinz.hlx3.page%2Fjp%2Fexpress%2Ffeature%3Flighthouse%3Don
> * `jpn-balanced-word-wrap`: https://pagespeed.web.dev/report?url=https%3A%2F%2Fjpn-balanced-word-wrap--express-website--masonpinz.hlx3.page%2Fjp%2Fexpress%2Ffeature%3Flighthouse%3Don
> 
> I can only assume it has to do with what's going on inside `bw.js`. Do you see a way to optimize the code do reduce blocking time?

Thank you very much for testing the performance, @rofe . I think you are right, the extra time in total blocking time must come from my code in bw2.js. However, upon my test, the variances of lighthouse scores of your two links above are very big, both main branch and my branch's total block time vary from 2xx ms to 1xxx ms. Do you have any way to see a more stable lighthouse score so that I can know how big the gap is exactly? I also tested using local dev server yesterday. I also couldn't get a significant difference between the page with/without my change. I suppose using of canvas must bring some slowness. Please help me to measure the gap if you have any clues.

2022-03-16 07:55 UTC, MasonPinZ commented
@rofe FYI these are the latest two runs of PSI in my browser.
<img width="500" alt="Screen Shot 2022-03-16 at 16 53 50" src="https://user-images.githubusercontent.com/12515123/158542546-2413d840-f9d6-4afd-8bf4-ad01c7b8cb2b.png">
<img width="500" alt="Screen Shot 2022-03-16 at 16 54 00" src="https://user-images.githubusercontent.com/12515123/158542555-79cbd7ba-3f26-47b9-92c5-c4bb46c17a17.png">

2022-03-16 10:32 UTC, rofe commented
@MasonPinZ thanks for looking into it. Unfortunately LHS variance can be high, but you can always compare the ranges from multiple runs between `main` and your branch.

Do you see a way to omit the use of canvas? Another solution could be to delay loading `bw.js` with a timeout.

cc @davidnuescheler

2022-03-16 11:04 UTC, MasonPinZ commented
@rofe , thanks for the advice! I confirmed that delaying the loading of bw2.js by 1 sec can reduce TBT from 140ms to 10ms in my local dev server, measured as an average of 10 runs of LHS. I'll keep looking ways to replace canvas.

2022-05-13 07:10 UTC, MasonPinZ commented
@rofe , this is now ready to merge. Regarding page loading performance, TBT is now 0ms on my local dev server. I also added unit tests for it. My QE colleague has also done a manual regression test. Can you merge it if everything looks good to you?

2022-05-16 05:46 UTC, rofe commented
@MasonPinZ Thank you very much for your valuable contribution!

2022-05-16 05:46 UTC, merged