CCX0022 Integration 2022-03-15
adobe/express-website pull request #372
Opened 2022-03-15 22:27 UTC by vgoodric

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-17 14:08 UTC, rofe commented
@vgoodric could you please fix the linting issues and add a test URL to the PR description?

2022-03-17 19:40 UTC, vgoodric commented
@rofe, @davidnuescheler  One of the pages with sixcols is this: https://www.adobe.com/express/create/flyer but I'm not sure if you mean the localhost address.  Truth is I still can't get the local installation to work.  So I can't test my code.  But I did just push an update where I moved the code to the template-list

2022-03-17 20:05 UTC, davidnuescheler commented
a test URL would be a helix URL that point to the branch, so we can all look at the code and see if it does what it is supposed to do... i this case it would be: https://ccx0022--express-website--adobe.hlx.page/express/create/flyer if that's page where we should see the changes....

2022-03-18 16:46 UTC, vgoodric commented
Eventual production url for QA: https://www.adobe.com/express/create/flyer
Test URL: https://ccx0022--express-website--adobe.hlx.page/express/create/flyer

2022-03-18 16:54 UTC, davidnuescheler approved these changes

2022-03-18 20:23 UTC, rofe approved these changes

2022-03-18 20:27 UTC, rofe commented
@vgoodric great job! The only thing missing to get this PR to green is you signing the [Adobe CLS](https://github.com/adobe/express-website/pull/372/checks?check_run_id=5603899066)

2022-03-19 00:46 UTC, vgoodric commented
@rofe ok, I've signed it

2022-03-21 15:15 UTC, rofe commented
@timliu-adobe this is ready to be pushed live. Is there a specific timing for the deployment, or asap?

2022-03-22 13:19 UTC, rofe requested changes

2022-03-22 13:19 UTC, rofe commented on express/blocks/template-list/template-list.css
> +  z-index: 1;
```suggestion
  z-index: 3;
```
Increase z-index to make sure scroll button stays above floating CTA button.

2022-03-23 13:58 UTC, timliu-adobe commented
hey @rofe @vgoodric—QA is complete for this, and we are good to push it live!

2022-03-23 16:17 UTC, merged