Ignore .idea files related to JetBrains IDE products
adobe/express-website pull request #378
Opened 2022-03-18 19:12 UTC by williambsm

Some developers work using JetBrains IDE and it would be good to be able to git ignore these files in order to avoid accidentally committing them to the project.

2022-03-18 19:24 UTC, rofe requested changes

2022-03-18 19:24 UTC, rofe commented on .gitignore
> +.vscode/*
Nitpicking: use the same folder path format throughout the file
```suggestion
.idea/
.vscode/
```

2022-03-18 19:25 UTC, rofe commented
@davidnuescheler, @tripodsan we may want to add this to the boilerplate also...

2022-03-18 20:17 UTC, tripodsan commented
> @davidnuescheler, @tripodsan we may want to add this to the boilerplate also...

sure.... but most people have `.idea` on their global gitignore anyways

2022-03-19 10:30 UTC, rofe approved these changes

2022-03-21 14:26 UTC, merged