feat(choose-your-path): customLink analytics
adobe/express-website pull request #497
Opened 2022-07-19 21:16 UTC by williambsm

Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=34618) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix MWPW-112424

Test URLs:
- https://mwpw-112424-a--express-website--webistry-development.hlx3.page/express/paths

This branch is meant to add analytics tracking to the slides on the Choose Your Path block.

2022-07-19 23:13 UTC, MarquiseRosier approved these changes
this looks great!

2022-07-19 23:43 UTC, MarquiseRosier requested changes
according to testing by @amauch-adobe folks are not sure the data is being seen on the other end!

2022-07-20 02:17 UTC, amauch-adobe commented
I tried testing Adobe Analytics by loading up the Adobe experience manager debugger extension in chrome. When I did load the extension and went to the testing URL the debugger stated that Adobe Analytics could not be found. I was going to ask William what exactly his code did. Looking at the pr for the code it looks like various <a> tags were added and a click tracking method but there wasn't anything else. So I wasn't sure what the click tracking method was/is supposed to do. Now granted I could be testing this incorrectly, but I felt that was how it should be tested. Anyone can correct me if I'm testing it wrongly or getting the wrong result.

See my screen recording down below.


https://user-images.githubusercontent.com/56042473/179880991-c620a796-83c3-4217-9f1a-e6e8ac0616d0.mov

2022-07-20 02:58 UTC, MarquiseRosier approved these changes

2022-07-20 02:58 UTC, merged