Mwpw 113319
adobe/express-website pull request #513
Opened 2022-08-11 17:01 UTC by qiyundai

Feat [MWPW 113319](https://jira.corp.adobe.com/browse/MWPW-113319)

Test URLs:

Before:
- https://main--express-website--webistry-development.hlx3.page/drafts/qiyundai/create/generic-app-store-highlight?lighthouse=on
- https://main--express-website--webistry-development.hlx3.page/drafts/qiyundai/create/top-use-case-test?lighthouse=on

After: 
- https://mwpw-113319--express-website--webistry-development.hlx3.page/drafts/qiyundai/create/generic-app-store-highlight?lighthouse=on
- https://mwpw-113696--express-website--webistry-development.hlx3.page/drafts/qiyundai/create/top-use-case-test?lighthouse=on

2022-08-11 19:49 UTC, rofe requested changes

2022-08-11 19:49 UTC, rofe commented on express/blocks/app-store-highlight/app-store-highlight.css
> +  -ms-overflow-style: none;  /* IE and Edge */
We don't support IE, and isn't Egde `chromium` these days? I think this can go...

2022-08-11 19:49 UTC, rofe commented on express/blocks/app-store-highlight/app-store-highlight.js
> + * Copyright 2021 Adobe. All rights reserved.
```suggestion
 * Copyright 2022 Adobe. All rights reserved.
```

2022-08-16 06:53 UTC, rofe requested changes
I'd simplify the authoring experience and use a two column layout in Word.

2022-08-16 06:53 UTC, rofe commented on express/blocks/app-store-highlight/app-store-highlight.css
> +  /*scroll-behavior: smooth;*/
```suggestion
```

2022-08-16 16:56 UTC, qiyundai commented
> I'd simplify the authoring experience and use a two column layout in Word.

Removed the score and count rows as they come from metadata sheet now.

2022-08-17 16:04 UTC, rofe approved these changes

2022-08-17 16:05 UTC, merged