fix(app-store-highlight): use optimized images
adobe/express-website pull request #530
Opened 2022-08-18 20:17 UTC by qiyundai

Fix MWPW-113319

Test URLs:
- Before: https://main--express-website--adobe.hlx.page/drafts/qiyundai/create/app-store-auto-blocks?lighthouse=on
- After: https://mwpw-113319--express-website--webistry-development.hlx.page/drafts/qiyundai/create/app-store-auto-blocks?lighthouse=on

2022-08-18 21:23 UTC, auniverseaway approved these changes

2022-08-18 22:10 UTC, amauch-adobe requested changes
See my comments below for issues I found with different browsers.

2022-08-18 22:53 UTC, amauch-adobe commented
@qiyundai, on Safari the QR code, bitly URL copy, and Google Play Store/ iPhone Store buttons get scrunched up.  I was running this Safari browser version:  Version 15.6 (17613.3.9.1.5) on a MacOS Monterrey v12.5

![Screen Shot 2022-08-18 at 4 10 01 PM](https://user-images.githubusercontent.com/56042473/185508469-4477f053-228a-4348-91b9-e1e866686be7.png)

Lastly, on all browsers, the Google Play Store button uses the exact same link as the Apple Store button link.  So instead of going to the Google Play store for the Adobe App, it goes to the Apple store.

Other than that everything is ready and good.

2022-08-19 06:45 UTC, rofe requested changes

2022-08-19 06:45 UTC, rofe commented on express/blocks/app-store-highlight/app-store-highlight.js
> +  '/drafts/qiyundai/fragments/media_1e1122a588f3d5d7e6f19e27aabf5102e72457b05.jpeg?width=380&format=jpeg&optimize=medium',
Don't use draft URLs for the images, but generic `/express/*` ones:
```suggestion
  '/express/media_1e71d9d4a13e8a8422dd1b8dbdad9a0bf4d2565f8.jpeg?width=380&format=jpeg&optimize=medium',
  '/express/media_1595dccf97b235679b21f3ccd02b20efddc3f3839.jpeg?width=380&format=jpeg&optimize=medium',
  '/express/media_1593e6a78c527e9799bb087cfcdb9d305a376123c.jpeg?width=380&format=jpeg&optimize=medium',
  '/express/media_1d3ae36afedf6def1703f32502b30e96a30d2c7a8.jpeg?width=380&format=jpeg&optimize=medium',
  '/express/media_1670698e01bd60bd8a2bc5b2e9c63b771dd9887e0.jpeg?width=380&format=jpeg&optimize=medium',
  '/express/media_1d8ff5ab0f17bf993dcd73f59e09c220a98dd9337.jpeg?width=380&format=jpeg&optimize=medium',
  '/express/media_169477a276ef70a1eb2b5b89a90d7eae6edd78e0c.jpeg?width=380&format=jpeg&optimize=medium',
  '/express/media_10c82ab880b3859c3850e1f6ece6fa57238b8af92.jpeg?width=380&format=jpeg&optimize=medium',
  '/express/media_1e1122a588f3d5d7e6f19e27aabf5102e72457b05.jpeg?width=380&format=jpeg&optimize=medium',
```

2022-08-19 14:29 UTC, rofe approved these changes

2022-08-19 14:29 UTC, merged