[MWPW-119603] CKG API Integration Part 2
adobe/express-website pull request #780
Opened 2023-03-28 20:23 UTC by qiyundai

Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=34618) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix [MWPW-119603](https://jira.corp.adobe.com/browse/MWPW-119603)

**Task description:**
Enhancement to the Link List powered by Browse API
- linklist-qa-mapping.json used for link pill text QA
- Search page now renders linklist pills correctly

**Test URLs:**
Before: https://main--express-website--adobe.hlx.page/express/templates/business-card
After: https://mwpw-119603--express-website--webistry-development.hlx.page/express/templates/business-card?lighthouse=on
Search Page: https://mwpw-119603--express-website--webistry-development.hlx.page/express/templates/business-card?lighthouse=on

2023-03-29 11:19 UTC, vhargrave requested changes
found a few things worth discussing - let me know what you think!

2023-03-29 16:27 UTC, qiyundai commented on express/scripts/api-v3-controller.js
> +      const resp = await fetch(`${urlPrefix}/express/linklist-qa-mapping.json`);
Makes perfect sense! The sheet currently is in express/ which is actually a locale directory. In the current setup, they'll need to duplicate this sheet for other locales when they think this feature is ready for other locales(we are not sure at the moment). If we were to move this sheet to the website/ which is the root for all locales, then we could avoid prepending urlPrefix.

2023-03-30 11:36 UTC, vhargrave approved these changes
looking good!

2023-03-30 11:37 UTC, vhargrave commented
@qiyundai it looks like there are merge conflicts, but after that we should be good to merge I think

2023-04-01 00:27 UTC, qiyundai commented
@vhargrave Might worth taking another look at this point... 😅

2023-04-03 19:03 UTC, qiyundai commented on express/scripts/templates.js
> +        col[1] = col[1].replace('{{placeholderRatio}}', params.phformat || '');
No. PlaceholderRatio is actually not used by the DOM so no need for grammar templating

2023-04-03 19:40 UTC, JingleH approved these changes
looks like people are blocked by this and it is already QAed, so I'm gonna go ahead and approve and merge. @vhargrave and @qiyundai you two feel free to continue any ongoing discussions and make changes later

2023-04-03 19:42 UTC, merged

2023-04-04 07:39 UTC, vhargrave commented
> looks like people are blocked by this and it is already QAed, so I'm gonna go ahead and approve and merge. @vhargrave and @qiyundai you two feel free to continue any ongoing discussions and make changes later

@JingleH I think it's good and bad we just merged. So probably for the best you just did it :P

2023-04-11 08:27 UTC, vhargrave commented
@JingleH no, but for the future I think we should be a little less trigger happy with the merge button